### ISSUE TITLE
dataset github release uzerinden indirebilir

### ISSUE THREAD

**Issue by fcakyon** [kadirnar/wideryolo#2]
@kadirnar oncelikle proje cok basarili, eline saglik 💯 

github repolarinda yeni release olustururken, dosya basina max 2gb limit ile dosya yuklemene izin veriyor. senin widerface train/val/test splitleri bu limitin altinda kaliyor. github release uzerinden host ederek google drive'in indirme limitinden kurtulabilirsin 👍

**Comment by kadirnar** [comment]
Çok teşekkür ederim. Drive üzerinden birkaç yöntem denedim ama başarılı olamamıştım. Bunu deneyeceğim.

**Comment by fcakyon** [comment]
@kadirnar github release uzerinden host edersen ekstra kutuphaneye gerek kalmadan basit bir get request ile indirebilirsin dosyalari. sahi'deki `download_from_url` fonksiyonunu kullanabilirsin: 

```python
from sahi.utils import download_from_url

download_from_url(from_url, to_path)
```

**Comment by kadirnar** [comment]
Sahi reposu bu konuda bana çok yardımcı oldu. download_datasets.py dosyasını yazarken sahi.utils dosyasından faydalandım. Sahi cidden çok güzel bir algoritma. 5 epoch da bile yüksek accuracy değerleri alabiliyorum.

**Comment by fcakyon** [comment]
@kadirnar sahi'yi cok guzel problemlere uyguluyorsun, calismalarini ilgiyle takip ediyorum :)

**Comment by kadirnar** [comment]
Zaman buldukça wider veri setinde farklı modellerin test işlemlerini gerçekleştireceğim. Sahi ile ilgili yapabileceğim test işlemi olursa seve seve denemek isterim.

**Comment by fcakyon** [comment]
@kadirnar calismalarinda basarilar!

- `sahi`, tum [mmdetection](https://github.com/open-mmlab/mmdetection) modellerini destekliyor. Oradaki obje tespiti modellerinden (yolox, yolof, yolov3, centernet, ssd, retinanet) egitim alarak sahi ile tespit performanslarini kiyaslayabilirsin.

- `sahi coco fiftyone` komutu ile modellerin tespit sonuclarini ve orijinal etiketleri acilan arayuzde gorsellestirebilirsin: https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-fiftyone-command-usage

- `sahi coco evaluate`, `sahi coco analyse` komutlari ile coco skorlarini hesaplayabilir, detayli hata raporlari olusturabilirsin: https://github.com/obss/sahi/blob/main/docs/CLI.md#coco-evaluate-command-usage

Sorun olursa https://github.com/obss/sahi uzerinde issue acabilirsin 💯

**Comment by kadirnar** [comment]
Sahi uygulandıktan sonra acc farkını merak ediyordum. sahi coco evaluate, sahi coco analyse modullerini denemek istiyorum. Bunun için veri seti coco json formatında olması şart mı?

**Comment by fcakyon** [comment]
@kadirnar evet coco formatinda olmasi sart.

`sahi`deki coco classlari ile cok kolay bir sekilde bir seti coco formatina cevirebilirsin. `sahi`reposundaki [COCO dataset creation](https://github.com/obss/sahi/blob/main/docs/COCO.md) basligindaki basamaklari takip etmen yeterli.

[visdrone](https://github.com/fcakyon/sahi-benchmark/blob/main/visdrone/visdrone_to_coco.py) ve [xview](https://github.com/fcakyon/sahi-benchmark/blob/main/xview/xview_to_coco.py) datasetleri icin `sahi` ile coco formatina cevirme kodlarini ornek alabbilirsin.

Biz `sahi`nin coco ap hesaplama ve hata analiz raporu olusturma scriptlerini gunluk olarak kullaniyoruz egittigimiz modellerin sonuclarini analiz ederken. Senin de islerinde faydasi olacaktir 👍

**Comment by kadirnar** [comment]
Teşekkür ederim @fcakyon hocam. Wider veri seti için coco formatını da paylaşacağım.
