### ISSUE TITLE
reponun secretslarina PYPI_API_TOKEN eklemek gerekiyor

### ISSUE THREAD

**Issue by fcakyon** [kadirnar/wideryolo#4]
Merhaba @kadirnar, tag sorunu cozulmus, simdi su hatayi veriyor action:

```bash
Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.
```

Bu warning yanlis tokeni kopyalamis olabilecegini gosteriyor.

```bash
Error during upload. Retry with the --verbose option for more details.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```

Bu hata gecerli bir api token verilmedigini gosteriyor.

https://pypi.org/ uzerinden API_TOKEN uretip bu reponun secretlarina PYPI_API_TOKEN adiyla dogru sekilde ekledin mi?

**Comment by kadirnar** [comment]
Token hatasını düzelttip yeni bir sürüm yayınladım fakat ````File already exists `` hatasını alıyorum bu hatanın sebebi ne olabilir?

**Comment by fcakyon** [comment]
@kadirnar 0.0.7 versiyonu ile publish ediyorsun pypi'ye: https://github.com/kadirnar/wideryolo/blob/4cc769a156951ba91499439ae262e61016e86fc1/setup.py#L11 ama pypi'de 0.0.7 zaten mevcut: https://pypi.org/project/wideryolo/0.0.7/

setup.py'daki versiyonu 0.0.8 yaparak yeni bir release aldiginda sorunsuz sekilde pypi'ye publish edecektir 👍

**Comment by kadirnar** [comment]
Hata düzeltilmiştir. Desteğin için teşekkür ederim
